import 'package:dartz/dartz.dart';
import 'package:injectable/injectable.dart';
import 'package:rxdart/rxdart.dart';

import '../../../../core/error/exceptions.dart';
import '../../../../core/utils/logger.dart';
import '../../../../core/error/failures.dart';
import '../../domain/entities/category.dart';
import '../../domain/repositories/category_repository.dart';
import '../datasources/category_remote_datasource.dart';
import '../models/category_model.dart';

/// Firestore implementation of [CategoryRepository].
@LazySingleton(as: CategoryRepository)
class CategoryRepositoryImpl implements CategoryRepository {
  final CategoryRemoteDataSource remoteDataSource;

  CategoryRepositoryImpl(this.remoteDataSource);

  @override
  Future<Either<Failure, List<Category>>> getCategories(String userId) async {
    try {
      final categories = await remoteDataSource.getCategories(userId);
      return Right(categories.map((m) => m.toEntity()).toList());
    } on ServerException catch (e) {
      return Left(ServerFailure(e.message));
    }
  }

  @override
  Stream<Either<Failure, List<Category>>> watchCategories(String userId) {
    return remoteDataSource
        .watchCategories(userId)
        .map<Either<Failure, List<Category>>>(
          (categories) => Right(categories.map((m) => m.toEntity()).toList()),
        )
        .onErrorResume((error, stackTrace) {
      AppLogger.debug('watchCategories error: $error');
      if (error is ServerException) {
        return Stream<Either<Failure, List<Category>>>.value(
            Left(ServerFailure(error.message)));
      }
      return Stream<Either<Failure, List<Category>>>.value(
          Left(ServerFailure('Unexpected error: $error')));
    });
  }

  @override
  Future<Either<Failure, Category>> createCategory(Category category) async {
    try {
      // Get next order value
      final nextOrder = await remoteDataSource.getNextOrderValue(category.userId);

      final model = CategoryModel(
        id: '', // Will be generated by Firestore
        name: _normalizeCategoryName(category.name),
        userId: category.userId,
        order: nextOrder,
        createdAt: DateTime.now(),
        lastUpdated: DateTime.now(),
      );

      final created = await remoteDataSource.createCategory(model);
      return Right(created.toEntity());
    } on ServerException catch (e) {
      return Left(ServerFailure(e.message));
    }
  }

  @override
  Future<Either<Failure, Category>> updateCategory(Category category) async {
    try {
      final model = CategoryModel(
        id: category.id,
        name: _normalizeCategoryName(category.name),
        userId: category.userId,
        order: category.order,
        createdAt: category.createdAt,
        lastUpdated: DateTime.now(),
        deletedAt: category.deletedAt,
      );

      final updated = await remoteDataSource.updateCategory(model);
      return Right(updated.toEntity());
    } on ServerException catch (e) {
      return Left(ServerFailure(e.message));
    }
  }

  @override
  Future<Either<Failure, void>> deleteCategory(String categoryId) async {
    try {
      await remoteDataSource.deleteCategory(categoryId);
      return const Right(null);
    } on ServerException catch (e) {
      return Left(ServerFailure(e.message));
    }
  }

  @override
  Future<Either<Failure, void>> reorderCategories(
    List<Category> categories,
  ) async {
    try {
      final models = categories
          .map((c) => CategoryModel.fromEntity(c))
          .toList();
      await remoteDataSource.reorderCategories(models);
      return const Right(null);
    } on ServerException catch (e) {
      return Left(ServerFailure(e.message));
    }
  }

  @override
  Future<Either<Failure, bool>> categoryNameExists(
    String userId,
    String name, {
    String? excludeId,
  }) async {
    try {
      final exists = await remoteDataSource.categoryNameExists(
        userId,
        name,
        excludeId: excludeId,
      );
      return Right(exists);
    } on ServerException catch (e) {
      return Left(ServerFailure(e.message));
    }
  }

  @override
  Future<Either<Failure, int>> getItemCountForCategory(
    String? categoryId,
    String userId,
  ) async {
    try {
      final count = await remoteDataSource.getItemCountForCategory(
        categoryId,
        userId,
      );
      return Right(count);
    } on ServerException catch (e) {
      return Left(ServerFailure(e.message));
    }
  }

  /// Normalizes a category name: trims whitespace and applies title case.
  String _normalizeCategoryName(String name) {
    final trimmed = name.trim();
    if (trimmed.isEmpty) return trimmed;

    // Title case: capitalize first letter of each word
    return trimmed.split(' ').map((word) {
      if (word.isEmpty) return word;
      return word[0].toUpperCase() + word.substring(1).toLowerCase();
    }).join(' ');
  }
}
