import 'package:dartz/dartz.dart';
import 'package:equatable/equatable.dart';
import 'package:injectable/injectable.dart';

import '../../../../core/error/failures.dart';
import '../../../../core/usecases/usecase.dart';
import '../../../../core/utils/validators.dart';
import '../entities/category.dart';
import '../repositories/category_repository.dart';

/// Parameters for [CreateCategoryUseCase].
class CreateCategoryParams extends Equatable {
  final String name;
  final String userId;

  const CreateCategoryParams({
    required this.name,
    required this.userId,
  });

  @override
  List<Object> get props => [name, userId];
}

/// Use case for creating a new category.
///
/// Validates:
/// - Name is not empty
/// - Name is max 30 characters
/// - Name is unique for the user
@lazySingleton
class CreateCategoryUseCase extends UseCase<Category, CreateCategoryParams> {
  final CategoryRepository repository;

  CreateCategoryUseCase(this.repository);

  @override
  Future<Either<Failure, Category>> call(CreateCategoryParams params) async {
    // Validate name
    final nameError = Validators.validateCategoryName(params.name);
    if (nameError != null) {
      return Left(ValidationFailure(nameError));
    }

    // Check for duplicate name
    final existsResult = await repository.categoryNameExists(
      params.userId,
      params.name,
    );

    // Handle failure case
    if (existsResult.isLeft()) {
      return Left(existsResult.fold((f) => f, (_) => const ServerFailure('')));
    }

    // Check if name already exists
    final exists = existsResult.getOrElse(() => false);
    if (exists) {
      return const Left(ValidationFailure(
        'A category with this name already exists',
      ));
    }

    // Create the category
    final now = DateTime.now();
    final category = Category(
      id: '', // Generated by Firestore
      name: params.name,
      userId: params.userId,
      order: 0, // Will be set by repository
      createdAt: now,
      lastUpdated: now,
    );

    return repository.createCategory(category);
  }
}
