import 'package:dartz/dartz.dart';
import 'package:equatable/equatable.dart';
import 'package:injectable/injectable.dart';

import '../../../../core/error/failures.dart';
import '../../../../core/usecases/usecase.dart';
import '../../../../core/utils/validators.dart';
import '../entities/item.dart';
import '../repositories/item_repository.dart';

/// Parameters for CreateItemUseCase.
///
/// Contains the required fields for creating a new item.
/// The id and timestamps will be generated by the repository.
class CreateItemParams extends Equatable {
  /// User-defined item name (will be validated)
  final String name;

  /// Initial count value (defaults to 0)
  final int initialValue;

  /// Amount to increment per event (1-100, will be validated)
  final int incrementBy;

  /// Type of reminder
  final ReminderType reminder;

  /// Threshold for reminders (0-1000, will be validated)
  final int reminderValue;

  /// Owner's Firebase UID
  final String userId;

  const CreateItemParams({
    required this.name,
    this.initialValue = 0,
    required this.incrementBy,
    required this.reminder,
    required this.reminderValue,
    required this.userId,
  });

  @override
  List<Object> get props => [
        name,
        initialValue,
        incrementBy,
        reminder,
        reminderValue,
        userId,
      ];
}

/// Use case for creating a new item.
///
/// Validates the item data before delegating to the repository.
/// Returns ValidationFailure if validation fails.
///
/// Validation rules:
/// - Name: Required, max 30 characters
/// - IncrementBy: 1-100 range
/// - ReminderValue: 0-1000 range
///
/// Example:
/// ```dart
/// final result = await createItemUseCase(CreateItemParams(
///   name: 'Coffee',
///   incrementBy: 1,
///   reminder: ReminderType.target,
///   reminderValue: 20,
///   userId: 'user_123',
/// ));
/// result.fold(
///   (failure) => print('Error: ${failure.message}'),
///   (item) => print('Created: ${item.name}'),
/// );
/// ```
@lazySingleton
class CreateItemUseCase extends UseCase<Item, CreateItemParams> {
  final ItemRepository repository;

  CreateItemUseCase(this.repository);

  @override
  Future<Either<Failure, Item>> call(CreateItemParams params) async {
    // Validate item name
    final nameError = Validators.validateItemName(params.name);
    if (nameError != null) {
      return Left(ValidationFailure(nameError));
    }

    // Validate increment value
    final incrementError = Validators.validateIncrementValue(params.incrementBy);
    if (incrementError != null) {
      return Left(ValidationFailure(incrementError));
    }

    // Validate reminder value
    final reminderError = Validators.validateReminderValue(params.reminderValue);
    if (reminderError != null) {
      return Left(ValidationFailure(reminderError));
    }

    // All validation passed, create the item
    // The repository will generate id and timestamps
    // lastResetTime is null for new items (never been reset)
    final now = DateTime.now();
    final item = Item(
      id: '', // Repository will generate
      name: params.name,
      count: params.initialValue,
      todayCount: params.initialValue,
      incrementBy: params.incrementBy,
      reminder: params.reminder,
      reminderValue: params.reminderValue,
      lastResetTime: null, // null = never reset
      lastUpdated: now,
      userId: params.userId,
    );

    return await repository.createItem(item);
  }
}
